database:
  host: {{ or .DATABASE_HOST "127.0.0.1" }}
  port: {{ or .DATABASE_PORT 5432 }}
  user: {{ or .DATABASE_USER "root" }}
  password: {{ or .DATABASE_PASSWORD "" }}
  database: {{ or .DATABASE_NAME "" }}
  pool: {{ or .DATABASE_POOL_SIZE 5 }}
  sslmode: {{ or .DATABASE_SSLMODE "disable" }}
server:
  host: {{ or .SERVER_BIND_ADDRESS "" }}
  port: {{ or .SERVER_BIND_PORT "8080" }}
manager:
  host: {{ or .MANAGER_BIND_ADDRESS "" }}
  port: {{ or .MANAGER_BIND_PORT "8081" }}
